# Generated by Django 4.2 on 2023-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
