# Generated by Django 4.2 on 2023-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shop', '0003_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
    ]
