# Generated by Django 4.2 on 2023-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shop', '0005_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeerMasServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=10000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='leerMasServicios')),
            ],
        ),
    ]
