# Generated by Django 4.2 on 2023-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=250)),
                ('mensaje', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
